### ISSUE TITLE
Data publicly available now (perhaps links could be added to Readme)

### ISSUE THREAD

**Issue by stheid** [gockelhahn/qual-o-mat-data#5]
The bpb seems to publish the data now after the pressure via frag-den-staat in form of .xlsx files.

Bundestagswahl is not yet online, which should be the case on the 2. september.

https://www.bpb.de/politik/wahlen/wahl-o-mat/berlin-2021/337699/download
https://www.bpb.de/system/files/datei/Wahl-O-Mat%20Berlin%202021_Datensatz.zip

Sorry for creating an "issue" but i thought it will interest most people that are interested in the data. perhaps it could be added to the Readme

**Comment by oyooyo** [comment]
> The bpb seems to publish the data now after the pressure via frag-den-staat in form of .xlsx files.

Ah, so that's why they're doing it. I had already wondered why the bpb provides that data for download now, when at the same time, they forbid to use it:

> **Jede Nutzung des Datensatzes, egal welcher Art, wird untersagt.**
(Quote from https://www.bpb.de/politik/wahlen/wahl-o-mat/berlin-2021/337699/download)

The german state's interpretation of "open data" is quite creative.

**Comment by gockelhahn** [comment]
thanks for creating this issue, i was indeed not aware of it! ... actually i wasnt expecting such a thing after their reluctance to do so for years (that was even the reason for creating this project) ... yeah, their "usage note" is hilarious :-1: 

anyhow, i added a hint in the readme and clarified why this repo is still important and will be continued! :100:
