### ISSUE TITLE
Access to statements

### ISSUE THREAD

**Issue by tazheinrich** [gockelhahn/qual-o-mat-data#6]
I'm looking for data on parties positions on statements for various elections. As far as I can tell, your repo is the only one collecting older versions of statements. However I'm not proficient in json data. How can I build a database off your data so I can for example calculate the percentage of overlap between two parties for any election?

**Comment by miwig** [comment]
@tazheinrich Are you still interested / did you figure it out? I might be able to offer assistance.

**Comment by tazheinrich** [comment]
I'm good. Thank you.
